# Generated by Django 3.1.3 on 2021-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('price', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
    ]
