# Generated by Django 3.1.3 on 2021-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('bprice', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='check',
        ),
    ]
